version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
  ignore:
  - dependency-name: Microsoft.CodeAnalysis.CSharp
    versions:
    - 3.8.0
  - dependency-name: Microsoft.ApplicationInsights
    versions:
    - 2.16.0
  - dependency-name: System.Diagnostics.EventLog
    versions:
    - 5.0.0
  - dependency-name: System.ServiceModel.Duplex
    versions:
    - 4.8.0
  - dependency-name: System.ServiceModel.Security
    versions:
    - 4.8.0
  - dependency-name: System.Private.ServiceModel
    versions:
    - 4.8.0
  - dependency-name: System.ServiceModel.Primitives
    versions:
    - 4.8.0
- package-ecosystem: nuget
  directory: "/tools/packaging/projects/reference/Microsoft.PowerShell.Commands.Utility"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
- package-ecosystem: nuget
  directory: "/tools/packaging/projects/reference/System.Management.Automation"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
- package-ecosystem: nuget
  directory: "/test/tools/Modules"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
- package-ecosystem: nuget
  directory: "/src/Modules"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - CL-BuildPackaging
